name: Sync master to local machine

on:
  push:
    branches:
      - master

jobs:
  sync:
    # 'ubuntu-latest' yerine 'self-hosted' yazıyoruz
    runs-on: self-hosted 

    steps:
      # Bu adım kodun en güncel halini bilgisayarındaki runner klasörüne çeker
      - name: Checkout code
        uses: actions/checkout@v4

      # Burada kendi proje klasörüne gidip pull yapabilirsin
      - name: Pull latest changes
        run: |
          cd ~/Projects/NewyorkCityTaxiTripSpark
          git pull origin master
